# Instroduction to scikit learn

this notebook demonstrates some of the most use full function of the beatuful sciket lean libary
What we're going to cover

0. An end to end Scikit learn workflow (workflow)
1. Getting the data ready
2. Choose the right estimator / algorithm for our problem
3. Fit the model alforithm and use it to make predictions on our data
4. Evaluating a model 
5. Improve model
6. Save and Load
7. Puting all together 

## End to End workflow

## 1. Get Data ready

In [1]:
import pandas as pd
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [2]:
# create X feature martrix
X = heart_disease.drop('target', axis=1)
# create y lables
Y = heart_disease["target"]

## 2. Choose the rigth model : we chosse RandomForestClassifier

In [3]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
# defaulte hyperparameter
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

## 3. Fit the model to train data

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [5]:
clf.fit(X_train, y_train);

### 3.1 Make prediction

In [6]:
y_preds = clf.predict(X_test)
y_preds

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [7]:
#evaluate the model
clf.score(X_train, y_train)

1.0

In [8]:
clf.score(X_test, y_test)

0.819672131147541

In [9]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.86      0.70      0.78        27
           1       0.79      0.91      0.85        34

    accuracy                           0.82        61
   macro avg       0.83      0.81      0.81        61
weighted avg       0.83      0.82      0.82        61



In [10]:
confusion_matrix(y_test, y_preds)

array([[19,  8],
       [ 3, 31]], dtype=int64)

In [11]:
accuracy_score(y_test, y_preds)

0.819672131147541

In [12]:
import numpy as np

In [13]:
# imporve a model
np.random.seed(42)

In [14]:
for i in range(10, 100, 10):
    print(f"try model with {i} estimatior")
    clf= RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy in test set : {clf.score(X_test, y_test)* 100}")

try model with 10 estimatior
Model accuracy in test set : 80.32786885245902
try model with 20 estimatior
Model accuracy in test set : 77.04918032786885
try model with 30 estimatior
Model accuracy in test set : 81.9672131147541
try model with 40 estimatior
Model accuracy in test set : 80.32786885245902
try model with 50 estimatior
Model accuracy in test set : 81.9672131147541
try model with 60 estimatior
Model accuracy in test set : 80.32786885245902
try model with 70 estimatior
Model accuracy in test set : 86.88524590163934
try model with 80 estimatior
Model accuracy in test set : 83.60655737704919
try model with 90 estimatior
Model accuracy in test set : 80.32786885245902


In [15]:
# save model

import pickle
pickle.dump(clf, open("random_forst_model_01.pkl","wb"))

In [16]:
load_model = pickle.load(open("random_forst_model_01.pkl", "rb"))
load_model.score(X_test, y_test)

0.8032786885245902

# 1. GET  DATA READY 
Three main thing we have to do:
   1. Split data into feature and labels (Usually 'X' and 'Y')
   2. Filling (also called imputing ) or disregarding missing values (fill missing data in data set)
   3. Converting non-numberical values to number values (also call feature encoding) (convert string or what ever to number)

###  1. Split data into feature and labels (Usually 'X' and 'Y')

In [45]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [46]:
X = heart_disease.drop(labels="target", axis=1) # remove target colum and choose axis 1 (colums)

In [47]:
X.head() # resulte remove

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [48]:
y = heart_disease['target'] # we use target for Y axis that why we remove from x first

In [49]:
# Split the data into traning and test sets 

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [24]:
X.shape

(303, 13)

In [25]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape # check this tuple is number for data to test

((242, 13), (61, 13), (242,), (61,))

In [26]:
X.shape[0] * 0.8 # for check data then we have  is 303  and we use 20 percent test_size(0.2) 

242.4

In [27]:
242+61 # 242 is 80 percent data ,61 is 20 percent test data

303

 ### 2. Filling (also called imputing ) or disregarding missing values (fill missing data in data set)

In [52]:
car_sales = pd.read_csv("car-sales-extended.csv")
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [53]:
car_sales.dtypes # we have Make and Colour stll not number

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [54]:
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [55]:
from sklearn.ensemble import RandomForestRegressor
# testing fit model with not cleanup string first 
model = RandomForestRegressor() 
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Nissan'

In [56]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# now we clean catalogies into number


# turn the catalogies into number

In [60]:
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                  one_hot,
                                 categorical_features)],
                               remainder="passthrough")
tranfrom_X = transformer.fit_transform(X)
tranfrom_X  # now it number

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [61]:
pd.DataFrame(tranfrom_X) # check dataset

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [62]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies # check dummy 

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [69]:
# Let refit the model
model = RandomForestRegressor()
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(tranfrom_X, y, test_size=0.2)
model.fit(X_train, y_train)

RandomForestRegressor()

In [70]:
model.score(X_test, y_test)

0.3235867221569877