In [2]:
import numpy as np

## Data types & Attribute

# Numpy main is data type is array 

In [5]:
a1 = np.array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [23]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [24]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [25]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [26]:
a2.shape

(2, 3)

In [27]:
a3.shape

(2, 3, 3)

In [28]:
a1.shape

(3,)

In [30]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [38]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [34]:
a3.dtype

dtype('int32')

In [36]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [37]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create datafrom

In [40]:
import pandas as pd

In [41]:
df = pd.DataFrame(a2)

In [42]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Create arrays

In [44]:
sample_array = np.array([1,2,3])

In [47]:
sample_array.dtype

dtype('int32')

In [51]:
ones = np.ones((5,6))

In [52]:
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [53]:
ones.dtype

dtype('float64')

In [54]:
type(ones)

numpy.ndarray

In [55]:
zeros = np.zeros((3,4))

In [56]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
range_array = np.arange(0,10,2)

In [60]:
range_array

array([0, 2, 4, 6, 8])

In [67]:
random_array = np.random.randint(0, 10, size=(4,5))

In [68]:
random_array

array([[5, 9, 3, 8, 3],
       [0, 9, 1, 5, 6],
       [1, 8, 3, 2, 2],
       [6, 5, 4, 7, 7]])

In [69]:
random_array.shape

(4, 5)

In [70]:
random_array.size

20

In [72]:
random_array_2 = np.random.random(size=(5,3))

In [73]:
random_array_2

array([[0.88761379, 0.16437119, 0.0048474 ],
       [0.78633609, 0.4973939 , 0.3471612 ],
       [0.1796329 , 0.24085237, 0.02762517],
       [0.1966068 , 0.84848712, 0.6113547 ],
       [0.26385407, 0.60291257, 0.7760127 ]])

In [74]:
random_array_2.shape

(5, 3)

In [75]:
random_array_3 = np.random.rand(5,3)

In [76]:
random_array_3

array([[0.38405196, 0.78881433, 0.22800544],
       [0.38255219, 0.02680185, 0.78743937],
       [0.52634703, 0.46662699, 0.3455876 ],
       [0.65343287, 0.92541477, 0.54159302],
       [0.66428797, 0.45596045, 0.06849477]])